### ISSUE TITLE
Tracking&Validation Database

### ISSUE THREAD

**Issue by dittmanndennis** [AWT-SS22-Track-Trace-3/backend#1]
EU Regulation (https://www.ema.europa.eu/en/human-regulatory/overview/public-health-threats/falsified-medicines-overview, https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv:OJ.L_.2016.032.01.0001.01.ENG):

- [x] Unique Identifier (consists of: Manufacturer product code, Serial Number, National reimbursement number (if present), Batch Number, Expiry Date) has to be created through import or by manufacturer,
- [x] verified at every wholesaler,
- [x] and checked out at use

US Regulation:

- [x] create validated entries
- [x] Parameter: unique serial number, manufacturer, list of wholesalers, product name, its strength and dosage form; its National Drug Code; container size and the number of containers; lot number; transaction date; shipment date; and the name and address of the businesses from which and to which ownership is being transferred. The TS is an attestation by the business transferring ownership of the product that it has complied with the DSCSA
- [ ] retain information for 6 years

**Comment by dittmanndennis** [comment]
wont be implementing kubernetes. therefore, we wont have access to cronjobs and not be able to auto delete after x amount of time. so, can we close this issue as well? @theEpsilon
